language: dart
dart:
    - stable
env:
    global:
        - ENCRYPTION_LABEL: "e850cfe3cd04"
install:
    - rvm use 2.1 --install --binary --fuzzy
    - gem install sass
script:
    - pub get
    - pub build --mode=release
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    local_dir: build/web
    on:
        branch: master
