language: dart
dart:
    - stable
env:
    global:
        - ENCRYPTION_LABEL: "e850cfe3cd04"
install:
    - rvm use 2.1 --install --binary --fuzzy
    - gem install sass
script:
    - pub get
    - pub build --mode=release
after_success:
    - bash ./scripts/deploy.sh
